const data = [
    {
        id: 1,
        name: 'Boku no Hero Academia vol.1',
        author: 'KOHEI HORIKOSHI',
        seriesName: 'Boku no Hero Academia',
        published: '2 september 2019',
        publisher: 'Siam Inter Comics',
        price: 70,
        page: 194,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/103174/Thumbnail/book_detail_large.gif?3',
        synopsis: 'Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasnt got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all, gives him a chance to change his destiny…',
        genre: ['action', 'adventure', 'drama', 'romance', 'harem', 'school life', 'fantasy']
    },
    {
        id: 2,
        name: 'Gintama vol.1',
        author: 'Hideaki Sorachi',
        seriesName: 'Gintama',
        published: '',
        publisher: '',
        price: 45,
        pages: 216,
        imageURL: 'https://images-na.ssl-images-amazon.com/images/I/51GG+W6mwAL._SX329_BO1,204,203,200_.jpg',
        synopsis: 'Set in Edo, which has been conquered by aliens named Amanto, the plot follows life from the point of view of samurai Gintoki Sakata, who works as a freelancer alongside his friends Shinpachi Shimura and Kagura to pay the monthly rent.',
        genre: ['action', 'adventure', 'drama', 'romance', 'harem', 'comedy', 'culture shock', 'fantasy', 'sci-fi', 'idol', 'role play']
    },
    {
        id: 3,
        name: 'One Piece vol.101',
        author: 'EIICHIRO ODA',
        seriesName: 'One Piece',
        published: '',
        publisher: '',
        price: 70,
        pages: 208,
        imageURL: 'https://images-na.ssl-images-amazon.com/images/I/511DhzXcziL._SX331_BO1,204,203,200_.jpg',
        synopsis: 'Monkey D. Luffy, a young man made of rubber, who, inspired by his childhood idol, the powerful pirate Red-Haired Shanks, sets off on a journey from the East Blue Sea to find the mythical treasure, the One Piece, and proclaim himself the King of the Pirates.',
        genre: ['action', 'adventure', 'drama', 'romance', 'comedy']
    },
    {
        id: 4,
        name: 'Naruto vol.1',
        author: 'Kishimoto Masashi',
        seriesName: 'Naruto',
        published: '',
        publisher: '',
        price: 70,
        pages: 192,
        imageURL: 'https://images-na.ssl-images-amazon.com/images/I/61LVJN2aIoL._SX331_BO1,204,203,200_.jpg',
        synopsis: 'Whenever Naruto Uzumaki proclaims that he will someday become the Hokage—a title bestowed upon the best ninja in the Village Hidden in the Leaves—no one takes him seriously. Since birth, Naruto has been shunned and ridiculed by his fellow villagers. But their contempt is not because Naruto is loud- mouthed, mischievous, or because of his ineptitude in the ninja arts, but because there is a demon inside him.Prior to Naruto is birth, the powerful and deadly Nine-Tailed Fox attacked the village. In order to stop the rampage, the Fourth Hokage sacrificed his life to seal the demon inside the body of the newborn Naruto.',
        genre: ['action', 'adventure', 'drama', 'romance', 'harem', 'comedy', 'i wants to be hokage']
    },
    {
        id: 5,
        name: 'Blue Exorcist vol.1',
        author: 'Katou Kazue',
        seriesName: 'Blue Exorcist',
        published: '',
        publisher: '',
        price: 70,
        pages: 202,
        imageURL: 'https://images-na.ssl-images-amazon.com/images/I/51cPh7AG6kL._SX331_BO1,204,203,200_.jpg',
        synopsis: 'After a fight with his foster father Shirou Fujimoto, Rin Okumura is life is transformed overnight when Rin is revealed to be the son of the demon lord Satan, king of the demonic realm of Gehenna.Soon after, his foster father becomes possessed and dies at the hands of Satan, leaving Rin and his twin brother Yukio alone in the world.Seeking revenge for Fujimoto is death, Rin attends True Cross Academy with Yukio in order to become an exorcist and join the Knights of the True Cross.',
        genre: ['action', 'adventure', 'drama', 'romance', 'school life']
    },
    {
        id: 6,
        name: 'Hunter x Hunter vol.1',
        author: 'Togashi Yoshihiro',
        seriesName: 'Hunter x Hunter',
        published: '19 September 2019',
        publisher: 'NED COMICS',
        price: 70,
        pages: 186,
        imageURL: 'https://images-na.ssl-images-amazon.com/images/I/51K4waiYZeL._SX331_BO1,204,203,200_.jpg',
        synopsis: 'Gon Freecss wants to become a Hunter so he can find his father, a man who abandoned him to pursue a life of adventure. But it is not that simple: only one in one hundred thousand can pass the Hunter Exam, and that is just the first obstacle on his journey.During the Hunter Exam, Gon befriends many other potential Hunters, such as the mysterious Killua; the revenge- driven Kurapika; and Leorio, who aims to become a doctor.There is a world of adventure and peril awaiting, and those who embrace it with open arms can become the greatest Hunters of them all',
        genre: ['action', 'adventure', 'drama', 'romance', 'school life']
    },
    {
        id: 7,
        name: 'Hunter x Hunter vol.2',
        author: 'Togashi Yoshihiro',
        seriesName: 'Hunter x Hunter',
        published: '19 September 2019',
        publisher: 'NED COMICS',
        price: 70,
        pages: 188,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/104620/Thumbnail/book_detail_large.gif?2',
        synopsis: 'Gon Freecss wants to become a Hunter so he can find his father, a man who abandoned him to pursue a life of adventure. But it is not that simple: only one in one hundred thousand can pass the Hunter Exam, and that is just the first obstacle on his journey.During the Hunter Exam, Gon befriends many other potential Hunters, such as the mysterious Killua; the revenge- driven Kurapika; and Leorio, who aims to become a doctor.There is a world of adventure and peril awaiting, and those who embrace it with open arms can become the greatest Hunters of them all',
        genre: ['action', 'adventure', 'drama', 'romance', 'school life']
    },
    {
        id: 8,
        name: 'Hunter x Hunter vol.3',
        author: 'Togashi Yoshihiro',
        seriesName: 'Hunter x Hunter',
        published: '19 September 2019',
        publisher: 'NED COMICS',
        price: 70,
        pages: 188,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/104621/Thumbnail/book_detail_large.gif?2',
        synopsis: 'Gon Freecss wants to become a Hunter so he can find his father, a man who abandoned him to pursue a life of adventure. But it is not that simple: only one in one hundred thousand can pass the Hunter Exam, and that is just the first obstacle on his journey.During the Hunter Exam, Gon befriends many other potential Hunters, such as the mysterious Killua; the revenge- driven Kurapika; and Leorio, who aims to become a doctor.There is a world of adventure and peril awaiting, and those who embrace it with open arms can become the greatest Hunters of them all',
        genre: ['action', 'adventure', 'drama', 'romance', 'school life']
    },
    {
        id: 9,
        name: 'Gotoubun no Hanayome vol.1',
        author: 'Negi Haruba',
        seriesName: 'Gotoubun no Hanayome',
        published: '19 June 2019',
        publisher: 'LUCKPIM Publishing',
        price: 45,
        pages: 194,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/97672/Thumbnail/book_detail_large.gif?5',
        synopsis: 'Fuutarou Uesugi is an ace high school student, but leads an otherwise tough life. His standoffish personality and reclusive nature have left him friendless, and his father is debt-ridden, forcing his family to scrape by.',
        genre: ['drama', 'romance', 'harem', 'school life', 'comedy']
    },
    {
        id: 10,
        name: 'Gotoubun no Hanayome vol.11',
        author: 'Negi Haruba',
        seriesName: 'Gotoubun no Hanayome',
        published: '19 June 2019',
        publisher: 'LUCKPIM Publishing',
        price: 55,
        pages: 196,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/115480/Thumbnail/book_detail_large.gif?2',
        synopsis: 'Fuutarou Uesugi is an ace high school student, but leads an otherwise tough life. His standoffish personality and reclusive nature have left him friendless, and his father is debt-ridden, forcing his family to scrape by.',
        genre: ['drama', 'romance', 'harem', 'school life', 'comedy']
    },
    {
        id: 11,
        name: 'Boku no Hero Academia vol.33',
        author: 'KOHEI HORIKOSHI',
        seriesName: 'Boku no Hero Academia',
        published: '2 september 2019',
        publisher: 'Siam Inter Comics',
        price: 70,
        pages: 196,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/208507/Thumbnail/book_detail_large.gif?2',
        synopsis: 'Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasnt got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all, gives him a chance to change his destiny…',
        genre: ['action', 'adventure', 'drama', 'romance', 'harem', 'school life']
    },
    {
        id: 12,
        name: 'Re: Starving Re: velation vol.1',
        author: 'YUU KURAISHI',
        seriesName: 'Re: Starving Re: velation',
        published: '21 september 2022',
        publisher: 'Vibulkij Publishing',
        price: 89,
        pages: 196,
        imageURL: 'https://cdn-local.mebmarket.com/meb/server1/210141/Thumbnail/book_detail_large.gif?2',
        synopsis: 'Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasnt got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all, gives him a chance to change his destiny…',
        genre: ['action', 'horor', 'thiller', 'sci-fi', 'school life']
    },
]

exports.data = data;